### ISSUE TITLE
Issue con fixnums...

### ISSUE THREAD

**Issue by Lowdive** [ahardencoopers/prfOperativos#21]
L 3
Liberando proceso 3
size 4
Fixnum Fixnum

**Comment by ahardencoopers** [comment]
Te sale con el archivo de pruebas del profe?

**Comment by Lowdive** [comment]
seh, igual si no te sale a tí, ha de ser mi versión de ruby o algo así.

On Thu, May 14, 2015 at 9:42 AM, Alberto Harden Cooper Saldívar <
notifications@github.com> wrote:

> Te sale con el archivo de pruebas del profe?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ahardencoopers/prfOperativos/issues/21#issuecomment-102056843
> .

## 

José Elí Santiago Rodríguez.
Disponibilidad de Horario.
https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week

**Comment by ahardencoopers** [comment]
Se supone que ahi deberia de liberar verdad.

**Comment by Lowdive** [comment]
nono, sí libera, pero esas variables que salen dicen fixnum fixnum, y size 4, algo se está pasando mal no?

**Comment by ahardencoopers** [comment]
Aaaaa las estaba usando de debugging, se me paso quitarlas, pero si funciona.

**Comment by Lowdive** [comment]
ahhh okok, pensé que se estaban pasando parámetros inválidos.

On Thu, May 14, 2015 at 9:46 AM, Alberto Harden Cooper Saldívar <
notifications@github.com> wrote:

> Aaaaa las estaba usando de debugging, se me paso quitarlas, pero si
> funciona.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ahardencoopers/prfOperativos/issues/21#issuecomment-102058507
> .

## 

José Elí Santiago Rodríguez.
Disponibilidad de Horario.
https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week

**Comment by ahardencoopers** [comment]
Y
