### ISSUE TITLE
Liberar no borra al proceso de listaProcesos

### ISSUE THREAD

**Issue by Lowdive** [ahardencoopers/prfOperativos#9]
se me pasó ese detalle, pero ya intenté con estos y no jala, no borra de la lista:
listaProcesos.delete("#{idProceso}")
o 
listaProcesos.delete(dProceso)
o
@listaProcesos.delete(dProceso)

**Comment by ahardencoopers** [comment]
Lo voy a checar.

**Comment by ahardencoopers** [comment]
Ya esta, ahora se quita la referencia a los procesos al momento de llamar liberarProceso de clase Manejador.rb

**Comment by Lowdive** [comment]
Tested on 38f2f4283fbcf9b37e5236a5dbf78a6c8c270619, eso de ponerles nil no va a jalar, porque sigue en la listaProcesos y al circular lista proceso no sabe qué hacer con nil value.

PASTEBIN: http://pastebin.com/L4sNxqhq

Creo que ya se me ocurrió qué hacer, intentaré delete.at a ver si jala.
Sugiero revertir ese cambio que hace que se hagan nil en la lista. Si no se puede así en corto yo ahorita lo sobre-escribo de todos modos.

**Comment by Lowdive** [comment]
solved in #10 , I think...
